[package]
name = "google-cloud-discovery-generator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "discogen"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
serde = {version="1.0", features = ["derive"]}
regex = "1.5"
structopt = "0.3"
anyhow = "1.0"
chrono = "0.4.19"
