[package]
edition = "2021"
name = "google-cloud-discovery-generator"
version = "0.1.0"

[[bin]]
name = "discogen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
regex = "1.9"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
structopt = "0.3"
